services:
  pz-server:
    build: .
    container_name: zomboid-test
    restart: unless-stopped
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
    volumes:
      - ./server-data:/home/steam/zomboid