services:
  pz-server:
    env_file:
      - .env
    build: .
    container_name: zomboid-test
    restart: unless-stopped
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
    volumes:
      - ./server-data:/home/steam/Zomboid
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_DIR=${INSTALL_DIR}